// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXRjo5Gh7HqMHZDxL9p35qIQqcj0sFFw0',
    appId: '1:359541927077:web:48c178bc89e93904c4714c',
    messagingSenderId: '359541927077',
    projectId: 'zeroscrap',
    authDomain: 'zeroscrap.firebaseapp.com',
    storageBucket: 'zeroscrap.appspot.com',
    measurementId: 'G-ZSFXS668CQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPR78ASIJdVUTmEnHMrlX_8_HqDXDO_Ik',
    appId: '1:359541927077:android:d6dd63caa731807cc4714c',
    messagingSenderId: '359541927077',
    projectId: 'zeroscrap',
    storageBucket: 'zeroscrap.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb-7FVKNLDEAl5pg5ZSB9zl0S5pexBTU4',
    appId: '1:359541927077:ios:842f32cb02c77a9bc4714c',
    messagingSenderId: '359541927077',
    projectId: 'zeroscrap',
    storageBucket: 'zeroscrap.appspot.com',
    iosClientId: '359541927077-6lp4hjab7jd6v04f8qvk0rc84q0qq596.apps.googleusercontent.com',
    iosBundleId: 'com.example.zeroScarp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb-7FVKNLDEAl5pg5ZSB9zl0S5pexBTU4',
    appId: '1:359541927077:ios:842f32cb02c77a9bc4714c',
    messagingSenderId: '359541927077',
    projectId: 'zeroscrap',
    storageBucket: 'zeroscrap.appspot.com',
    iosClientId: '359541927077-6lp4hjab7jd6v04f8qvk0rc84q0qq596.apps.googleusercontent.com',
    iosBundleId: 'com.example.zeroScarp',
  );
}
